DELETE http://localhost:3003/api/persons/3

###
POST http://localhost:3003/api/persons
Content-Type: application/json

{
    "name": "Fabian",
    "number": "041-1234568"
}

###
POST http://localhost:3003/api/persons
Content-Type: application/json

{
    "name": "King",
    "number": "051-22355568"
}

###
POST http://localhost:3003/api/persons
Content-Type: application/json

{
    "name": "King",
    "number": "051-22355568"
}

###
POST http://localhost:3003/api/persons
Content-Type: application/json

{
    "number": "051-22355568"
}

###
POST http://localhost:3003/api/persons  
Content-Type: application/json

{
    "name": "Alice"
}

###
POST http://localhost:3003/api/persons
Content-Type: application/json  

{
    "name": "Nzube Obi",
    "number": "07078576246"
}

###
GET https://phonebook-app-6vzh.onrender.com

###
DELETE http://localhost:3003/api/persons/690ed7d2683c5a3657575e3e

###

PUT http://localhost:3003/api/persons/690c150f8656c1c76dae64a7
Content-Type: application/json

{
    "name": "Nobert",
    "number": "08012345678"
}   

###
POST http://localhost:3003/api/persons
Content-Type: application/json

{
    "name": "Ju",
    "number": "07056789123"
}   